Repository ya-masterskaya-cpp/q2_2025_chat_project_team_3, pull requests merged in 2025-07, with the labels that each got.

#157 Feature: Proper room memberships
  client/include/client/roomsPanel.h
  client/include/client/wsClient.h
  client/src/roomsPanel.cpp
  client/src/wsClient.cpp
  common/protobuf/chat.proto
  server/include/server/chat/MessageHandlers.h
  server/src/chat/MessageHandlerService.cpp
  server/src/chat/MessageHandlers.cpp
Labels: prio:high, feature

#158 Chore: Bump version before release
  CMakeLists.txt
  Doxyfile
  common/include/common/version.h
  vcpkg.json
Labels: prio:high

#161 Feature: User account settings (change username/password)
  client/CMakeLists.txt
  client/include/client/accountSettings.h
  client/include/client/chatPanel.h
  client/include/client/mainWidget.h
  client/include/client/message.h
  client/include/client/messageView.h
  client/include/client/messageWidget.h
  client/include/client/roomsPanel.h
  client/include/client/userListPanel.h
  client/include/client/wsClient.h
  client/src/accountSettings.cpp
  client/src/chatPanel.cpp
  client/src/mainWidget.cpp
  client/src/messageView.cpp
  client/src/messageWidget.cpp
  client/src/roomsPanel.cpp
  client/src/userListPanel.cpp
  client/src/wsClient.cpp
  common/protobuf/chat.proto
  server/include/server/chat/MessageHandlers.h
  server/src/chat/MessageHandlerService.cpp
  server/src/chat/MessageHandlers.cpp
Labels: prio:normal, task, feature

#163 Feature : Online user counting
  client/include/client/user.h
  client/src/userListPanel.cpp
  client/src/userNameWidget.cpp
  client/src/wsClient.cpp
  common/protobuf/chat.proto
  server/src/chat/MessageHandlers.cpp
Labels: prio:high, feature, UI
